/**
 * backend/prisma/seeds/dailyQuotes.ts  — T084
 *
 * 365 frases inspiradoras em PT-BR para o banco DailyContent.
 * Cada registro usa uma data sequencial começando em 2026-01-01.
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const QUOTES: string[] = [
  "Os astros não determinam seu destino — revelam seus talentos ocultos.",
  "Cada planeta em seu lugar conta uma história única sobre quem você é.",
  "O céu do seu nascimento é um mapa, não uma sentença.",
  "Nas estrelas não há acidentes, apenas padrões esperando ser compreendidos.",
  "Seu ascendente é a máscara que o mundo vê; seu Sol, quem você realmente é.",
  "A Lua governa as marés e também as suas emoções mais profundas.",
  "Mercúrio não retrograda para atrapalhar — retrograda para que você revise.",
  "Vênus em harmonia é música; Vênus em tensão é a letra que precisava ser escrita.",
  "Marte te move; Júpiter te expande; Saturno te constrói.",
  "O universo fala em símbolos. A astrologia é o dicionário.",
  "Não existe mapa astral ruim — existe energia ainda não compreendida.",
  "Cada retrogradação é um convite à introspecção, não ao caos.",
  "Seu signo solar é o personagem; sua Lua é a alma; o ascendente é o figurino.",
  "As estrelas inclinam, mas não obrigam.",
  "Plutão transforma o que toca. Deixe-o fazer seu trabalho.",
  "A conjunção de dois planetas é o universo criando novas possibilidades.",
  "Saturno em trânsito não pune — ensina com rigor.",
  "Netuno dissolve fronteiras para que você enxergue além das aparências.",
  "Urano traz liberdade onde havia estagnação.",
  "Júpiter é o professor generoso — ele expande o que você já é.",
  "Na astrologia, o tempo perfeito é aquele que chega quando você está pronto.",
  "O signo é a cor; o planeta é o pincel; você é o artista.",
  "Aries inicia o que Peixes sonhou. O ciclo continua.",
  "Touro sabe que a beleza está nos detalhes que o olhar apressado ignora.",
  "Gêmeos vive duas vidas em uma só conversa.",
  "Câncer guarda o passado para transformá-lo em lar.",
  "Leão brilha não para ser visto, mas porque não sabe fazer diferente.",
  "Virgem não busca perfeição — busca significado no que faz.",
  "Libra sabe que o equilíbrio não é imobilidade, é dança.",
  "Escorpião mergulha fundo porque acredita que a superfície não é suficiente.",
  "Sagitário voa porque sabe que o horizonte sempre tem novidades.",
  "Capricórnio constrói com paciência o que dura séculos.",
  "Aquário imagina mundos que ainda não existem para depois criá-los.",
  "Peixes sente o que outros não conseguem nomear.",
  "Cada eclipse é um portal para uma nova versão de si mesmo.",
  "A Lua Nova planta; a Lua Cheia colhe. Qual ciclo você está vivendo?",
  "O mapa astral não é um teto — é o ponto de partida.",
  "Confie nos seus ciclos como confia nas estações do ano.",
  "A crise de Saturno é o treino que você precisava, não o fim.",
  "Quando Vênus transita, o coração fica mais vulnerável e mais aberto.",
  "Marte em aspecto difícil não é inimigo — é o combustível disfarçado.",
  "Os trânstios planetários são capítulos. Você é o protagonista.",
  "Uma vida sem introspecção é como navegar sem mapa astral.",
  "O universo tem pressa zero. Alinhe seu ritmo ao ritmo cósmico.",
  "Nascer sob determinados astros é receber um presente que leva a vida toda para ser aberto.",
  "Nem todo trígono é fácil; nem toda quadratura é difícil. A intenção importa.",
  "Você não está perdido — está em trânsito.",
  "A oposição planetária é o universo pedindo que você veja pelos dois lados.",
  "Cuide da sua Lua como cuida das suas emoções: com gentileza e atenção.",
  "O sextil oferece oportunidade; cabe a você usá-la.",
  "Saturno demora, mas entrega o que realmente construiu.",
  "Cada carta astral é uma obra de arte única — e você é o curador da sua.",
  "Não compare seu mapa ao de ninguém. Você não tem o mesmo céu.",
  "O tempo certo não é o mais rápido — é o mais alinhado.",
  "Ascendente em fogo: presença que aquece qualquer ambiente.",
  "Ascendente em terra: solidez que sustenta os que chegam.",
  "Ascendente em ar: curiosidade que renova as conversas.",
  "Ascendente em água: sensibilidade que toca sem precisar falar.",
  "Planetas em ângulos falam mais alto — aqui está o seu palco.",
  "Planeta dominante: o instrumento que toca com mais naturalidade.",
  "A casa Doze não é a casa do fim — é a da renovação silenciosa.",
  "Na casa Um você se apresenta; na casa Doze você se prepara.",
  "Os nodos lunares apontam de onde viemos e para onde crescemos.",
  "O eixo ASC-DSC revela como você ama e como é amado.",
  "A Lua Negra Lilith é a parte de você que não pede desculpas por existir.",
  "O Quíron é a ferida que, curada, vira dom.",
  "Júpiter em bom aspecto com a Lua: otimismo emocional que contagia.",
  "Saturno conjunção Netuno: construir sonhos com tijolos reais.",
  "Marte trígono Júpiter: energia com propósito e sem desperdício.",
  "Vênus quadratura Plutão: amor que transforma, mesmo doendo.",
  "Sol oposição Lua: integrar ação e emoção, razão e instinto.",
  "Mercúrio sextil Urano: mente brilhante, conexões inesperadas.",
  "Cada volta de Júpiter ao seu lugar natal marca um novo ciclo de doze anos.",
  "O retorno de Saturno é o universo exigindo que você cresça de verdade.",
  "Progresso lunário: a Lua que você se torna ao longo do tempo.",
  "As direções primárias são o relógio lento do destino.",
  "Assuntos de Marte: coragem, ação, desejo, competição.",
  "Assuntos de Vênus: amor, beleza, dinheiro, prazer.",
  "Assuntos de Mercúrio: comunicação, viagens curtas, aprendizado.",
  "Assuntos de Júpiter: expansão, fé, filosofia, generosidade.",
  "Assuntos de Saturno: limite, tempo, responsabilidade, estrutura.",
  "Assuntos do Sol: essência, vitalidade, propósito, paternidade.",
  "Assuntos da Lua: emoções, memória, lar, maternidade.",
  "A astrologia não é destino; é diálogo com o possível.",
  "Estar alinhado com os astros é estar alinhado com seu ritmo mais profundo.",
  "Onde há tensão no mapa, há potencial em compressão.",
  "A quadratura é o conflito que gera a força do diamante.",
  "O trígono flui; a quadratura forja; a oposição ensina.",
  "O signo solar é quem você é; o signo lunar é o que você precisa.",
  "Sua parte da fortuna indica onde encontrar alegria genuína.",
  "O Meio do Céu é o ápice da sua missão pública.",
  "O IC é a raiz; O MC é o fruto. Cuide de ambos.",
  "Cada Casa é um teatro diferente; os planetas, os atores.",
  "Casa Um: sua aparência e impulso vital.",
  "Casa Dois: seus recursos e valores fundamentais.",
  "Casa Três: sua comunicação e mundo imediato.",
  "Casa Quatro: sua origem, lar e raízes emocionais.",
  "Casa Cinco: sua criatividade, amor e prazer.",
  "Casa Seis: seu trabalho cotidiano e saúde.",
  "Casa Sete: suas parcerias e o espelho do outro.",
  "Casa Oito: transformação, recursos compartilhados, mistérios.",
  "Casa Nove: filosofia, viagens longas, expansão de horizontes.",
  "Casa Dez: carreira, status e legado público.",
  "Casa Onze: grupos, amizades, sonhos coletivos.",
  "Casa Doze: retiro, inconsciente, karma e renovação.",
  "Quando o professor está pronto, o aluno surge. Quando o aluno está pronto, Saturno aparece.",
  "A astrologia médica antiga dizia: cada signo governa uma parte do corpo. Cuide do todo.",
  "Na mundana, os astros governam nações. Em você, governam intenções.",
  "O horóscopo diário é um convite à consciência, não uma profecia.",
  "Prevermos os ciclos não para escapar deles, mas para surfá-los.",
  "Dois mapas em sinastria: dois universos aprendendo a orbitar juntos.",
  "A sinastria revela não quem é o parceiro certo — mas o que a relação ativará em você.",
  "Um aspecto difícil entre dois mapas não é incompatibilidade; é área de crescimento compartilhado.",
  "Vênus de um conjunta ao Sol do outro: o coração reconhece antes da mente.",
  "Saturno de um sobre o Vênus do outro: amor que amadurece com comprometimento.",
  "O sol e a lua em boa sinastria: dia e noite que se completam.",
  "No composto, nasce um terceiro planeta: a entidade chamada 'nós'.",
  "Boa sinastria não garante facilidade — garante que vale a pena enfrentar o difícil.",
  "O signo Interceptado pede atenção especial — está esperando para se expressar.",
  "Cada planeta na Fronteira (cúspide) carrega a energia de duas casas.",
  "A velocidade do planeta determina a profundidade da mudança.",
  "Ciclos lunares são os menores relógios do universo. Sincronize-se.",
  "Lua Nova: semear intenções com precisão e fé.",
  "Lua Crescente: agir, construir, dar forma ao que foi semeado.",
  "Quarto Crescente: ajustar o que não está funcionando sem abandonar o projeto.",
  "Lua Cheia: iluminar o que estava oculto, colher o maduro.",
  "Quarto Minguante: agradecer, soltar, criar espaço para o próximo ciclo.",
  "Lua Minguante: rever, curar, liberar o que não serve mais.",
  "Lua Balsâmica: descansar, sonhar, preparar o terreno da próxima Lua Nova.",
  "O eclipse solar é um reset; o lunar, uma revelação.",
  "Eclipse em seu Sol: um capítulo da identidade se fecha para outro se abrir.",
  "Eclipse em sua Lua: as emoções que você ignorava pedem palco.",
  "Quando um eclipse ativa seu Ascendente, o mundo enxerga você diferente.",
  "Saros: cada eclipse faz parte de uma série de 18 anos. O que começou?",
  "Os nodos lunares são eixo de evolução: Nodo Norte aponta o futuro; Sul, os dons do passado.",
  "Nodo Norte em Áries: sua missão é aprender a liderar sem precisar de aprovação.",
  "Nodo Norte em Touro: sua evolução passa por construir segurança e prazer autêntico.",
  "Nodo Norte em Gêmeos: crescer pela curiosidade, não pela certeza prévia.",
  "Nodo Norte em Câncer: nutrir e ser nutrido é o caminho da alma.",
  "Nodo Norte em Leão: sua expansão está em brilhar sem pedir permissão.",
  "Nodo Norte em Virgem: a maestria está nos detalhes e no serviço com amor.",
  "Nodo Norte em Libra: aprender a co-criar em vez de fazer tudo sozinho.",
  "Nodo Norte em Escorpião: mergulhar no desconhecido é a direção da sua alma.",
  "Nodo Norte em Sagitário: confiar na visão maior mesmo sem o mapa completo.",
  "Nodo Norte em Capricórnio: construir com responsabilidade é sagrado.",
  "Nodo Norte em Aquário: seu crescimento está na visão coletiva e na originalidade.",
  "Nodo Norte em Peixes: confiar na intuição e na fé, mais que no controle.",
  "As fixas guardam; as mutáveis adaptam; as cardinais iniciam.",
  "Signos de fogo: inspiração que ilumina o caminho dos outros.",
  "Signos de terra: sabedoria que transforma visão em realidade.",
  "Signos de ar: pensamento que conecta o que parecia separado.",
  "Signos de água: sentimento que alcança o que a lógica não toca.",
  "Terra planta, água nutre, fogo aquece, ar dissemina.",
  "Todos os elementos no mapa significam versatilidade.",
  "Falta de terra: aprender o valor do concreto e do tangível.",
  "Falta de água: cultivar a empatia e o mundo interior.",
  "Falta de fogo: acender a chama da motivação e da ação.",
  "Falta de ar: desenvolver a comunicação e a perspectiva objetiva.",
  "A dominância de um elemento é um superpoder e um ponto cego.",
  "Solo — sem aspectos — significa autonomia radical e isolamento igualitário.",
  "O planeta mais elevado do mapa tem uma missão social.",
  "O planeta mais baixo no mapa trabalha em camadas profundas e invisíveis.",
  "Planeta em Exaltação: em casa de hóspedes perfeita, expressando seu melhor.",
  "Planeta em Domicílio: em sua própria casa, à vontade e soberano.",
  "Planeta em Queda: fora do conforto, mas nem por isso sem poder.",
  "Planeta em Detrimento: aprendendo a se expressar em terreno adverso.",
  "A dignidade do planeta não é fraqueza ou força — é contexto.",
  "Astrologia Védica e Ocidental são dois idiomas descrevendo o mesmo universo.",
  "A Astrologia Chinesa usa ciclos de doze anos; a Ocidental usa doze signos.",
  "Astrologia evolucionária: o mapa como história da alma ao longo de vidas.",
  "Heliocentrismo e geocentrismo: perspectivas diferentes, sabedorias complementares.",
  "Os asteroides — Ceres, Pallas, Juno, Vesta — adicionam nuances ao mapa.",
  "Ceres: nutrição, ciclos de perda e renovação.",
  "Pallas: estratégia, sabedoria criativa, defesa sem violência.",
  "Juno: compromisso, parceria igualitária e lealdade.",
  "Vesta: devoção, foco sagrado e chama interior.",
  "Quiron, o 'planeta ferida': onde você sangrou é onde você cura outros.",
  "Cada geração carrega o espírito de Plutão, Urano e Netuno de forma coletiva.",
  "Geração Plutão-Escorpião: transformação do poder e da intimidade.",
  "Geração Plutão-Sagitário: questionando crenças globais e expandindo fronteiras.",
  "Geração Plutão-Capricórnio: reconstruindo estruturas que não servem mais à humanidade.",
  "Urano em Touro: revolução nos valores, dinheiro e relação com a terra.",
  "Netuno em Peixes: dissolução de fronteiras espirituais e ilusões coletivas.",
  "Cada era de Júpiter dura 12 anos: o que você expandiu neste ciclo?",
  "O retorno solar é o seu Ano Novo pessoal — um novo capítulo começa.",
  "A Lua Progressada muda de signo a cada dois anos e meio: novos humores, novas prioridades.",
  "A profissão Sol Progressado ilumina uma nova face da sua identidade a cada 30 anos.",
  "Retorno de Saturno: o grande julgamento dos 29, 58 e 87 anos de vida.",
  "Após o Retorno de Saturno, você passa a operar com muito mais autoridade.",
  "Júpiter retorna ao lugar natal a cada 12 anos — época de expansão e oportunidades.",
  "A oposição de Júpiter ao natal aos 6 e 18 anos: a adolescência tem um fundamento cósmico.",
  "Ao completar 42 anos, Urano faz sua oposição — o famoso 'despertar da meia-vida'.",
  "O sextil de Netuno ao natal: aos 14 e 70 anos, a espiritualidade chama.",
  "A crise de Plutão aos 36-40 anos: a sombra se torna inevitável e depois, libertadora.",
  "Cada geração tem seu Plutão, mas cada um tem seu próprio caminho de transformação.",
  "Não tema o vazio entre os ciclos — é lá que nasce o próximo florescimento.",
  "O mapa natal não muda; você muda o que faz com ele.",
  "Estudar astrologia é aprender o idioma com que o cosmos conversa com você.",
  "A carta astral é uma fotografia do céu no momento em que você virou luz.",
  "Você nasceu sob um arranjo singular de planetas que nunca se repetirá exatamente.",
  "Cada grau do zodíaco é uma vibração diferente — seu planeta a sintonizou em uma delas.",
  "Grau 0 de qualquer signo: começo puro, sem história, repleto de potencial.",
  "Grau 29 de qualquer signo: intensidade máxima, síntese de todo o aprendizado do signo.",
  "Os graus críticos carregam uma responsabilidade simbólica especial.",
  "Os graus Anaretas (0 e 29) são pontos de virada no desenvolvimento do planeta.",
  "As fixas Aldebaran, Regulus, Antares e Fomalhaut marcam os pontos reais do zodíaco.",
  "Estrela fixa conjunta a planeta: destino que vai além do ordinário.",
  "O Ascendente é o leste do seu mundo interno — onde o sol nasce em você.",
  "O Descendente é o que você atrai nos outros sem perceber que também é seu.",
  "Planetas na casa Sete: o que você projeta nos parceiros e precisa integrar.",
  "Stellium: concentração de energia em uma área — poderosa, intensa, transformadora.",
  "Stellium em Áries: impulso concentrado; stellium em Virgem: análise profunda.",
  "Grande Trígono: fluxo e facilidade — mas facilidade pode se tornar comodidade.",
  "T-quadrado: dois planetas em oposição, ambos quadrados a um terceiro. Tensão que move.",
  "Cruz Cármica: quatro planetas em quadratura — desafio de integração em múltiplas frentes.",
  "Grande Cruz: um dos padrões mais desafiantes e mais poderosos do mapa.",
  "Yod: o Dedo de Deus — dois sextis que apontam para um vértice. Missão específica.",
  "Kite: Grande Trígono com oposição — facilidade com direção e propósito.",
  "Mjolnir (Martelo de Thor): configuração de tensão aguda que rompe padrões.",
  "O Místico Retângulo equilibra tensão e fluxo em quatro cantos do mapa.",
  "Cada aspecto é uma conversa entre dois planetas — às vezes concorda, às vezes disputa.",
  "Um mapa sem quadraturas é um mapa sem muito o que superar — e superar é crescer.",
  "Valorize os aspectos difíceis: eles constroem o caráter que os fáceis não constroem.",
  "A astrologia humanística vê o mapa como potencial, não como fado.",
  "Dane Rudhyar: 'O mapa astral é o design de um ser tornando-se consciente de si mesmo.'",
  "Você não precisa acreditar nos astros para que eles influenciem os ritmos da sua vida.",
  "A maré sobe sem precisar que o peixe acredite na Lua.",
  "Conheça seu mapa não para se limitar, mas para se liberar com mais consciência.",
  "Cuide das energias em tensão no mapa como cuida de músculos: exercite, não evite.",
  "Cada trânsito difícil é um personal trainer cósmico que você não contratou mas precisa.",
  "Em cada dificuldade planetária há uma pergunta: o que você ainda não aprendeu sobre isso?",
  "Confie nos seus eclipses pessoais: eles apagam a luz antiga para que outra possa nascer.",
  "As maiores viradas da vida frequentemente acontecem sob eclipses ou trânsitos de Plutão.",
  "Você é muito mais do que seu signo solar. Você é todo o seu mapa.",
  "Converse com o seu mapa como conversaria com um espelho sábio.",
  "Que esta data seja fértil para as intenções que você planta com consciência.",
  "Cada amanhecer é uma nova oportunidade de ser fiel ao seu mapa natal.",
  "Os astros se alinham. Você faz o resto.",
  "O zodíaco gira, mas o centro sempre foi e sempre será você.",
  "Que os planetas de hoje iluminem o melhor de quem você já é.",
  "Boa jornada sob este céu. Os astros caminham com você.",
];

export async function seedDailyQuotes(): Promise<void> {
  console.log("🌟 Seeding daily quotes (DailyContent)…");

  const baseDate = new Date("2026-01-01T12:00:00Z");

  let created = 0;
  let skipped = 0;

  for (let i = 0; i < 365; i++) {
    const date = new Date(baseDate);
    date.setUTCDate(date.getUTCDate() + i);
    const dateOnly = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()));

    const quote = QUOTES[i % QUOTES.length]!;

    try {
      await prisma.dailyContent.upsert({
        where:  { date: dateOnly },
        update: { inspirationalQuote: quote },
        create: {
          date:               dateOnly,
          planet:             "sun",
          planetInfluence:    "Calculado dinamicamente.",
          moonPhase:          "new_moon",
          moonDescription:    "Calculado dinamicamente.",
          moonNextCycle:      dateOnly,
          inspirationalQuote: quote,
          alerts:             [],
        },
      });
      created++;
    } catch {
      skipped++;
    }
  }

  console.log(`✅ Daily quotes: ${created} upserted, ${skipped} errors.`);
}
